# Wprowadzenie

Numpy jest biblioteką służącą do przeprowadzania zaawansowanych operacji matematycznych i działań na macierzach. Poniżej przejdziemy przez podstawowe własności macierzy wielowymiarowych i sposoby operowania na nich.

In [2]:
# Import biblioteki
# nadajemy tzw. alias "np" czyli skrót bibliotece, żeby nie pisać za dużo :D

import numpy as np

# Tablice i macierze wielowymiarowe

Tablice wielowymiarowe tworzymy porpzez wywołanie funkcji:


```{python}

np.array( LISTA )

```

W miejsce listy przekazujemy oczywiście bazową listę, którą chcemy przekształcić.


In [3]:
# Tworzenie tablicy wielowymiarowej 

# Podstawowa, "bazowa" lista
lst = [1,2,3]

# Utworzenie tablicy wielowymiarowej w numpy
ar = np.array(lst)
ar

array([1, 2, 3])

In [5]:
# Sprawdzenie kształtu tablicy
ar.shape

(3,)

Tworzymy macierz dwuwymiarową, przez przekazanie odpowiednej "listy list".

In [6]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
])

In [7]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matrix.shape

(3, 3)

Do poszczególnych elementów macierzy odwołujemy się w sposób następujący:


ar**[**  *WIERSZE*  , *KOLUMNY*  **]**

Przecinek oddziela nam poszczególne wymiary: wiersze **,** kolumny.

Odwoływać się możemy na kilka sposobów:

> Pobieranie jednego elementu pod konkretnym indeksem - **podajemy konkretny indeks**

> ```{python}

> matrix [   LICZBA, LICZBA    ]

> ```


> Pobieranie wszystkich wierszy/kolumn - używamy **dwukropka** (oznacza "daj mi wszystko")
> ```{python}
>  matrix [  :,   LICZBA/BY ] - weź wszystkie wszystkie wiersze (wartości) z określonej kolumny/kolumn
>  matrix [  LICZBA/BY,  :  ] - weź wszystkie kolumny (wartości) z określonych wierszy/sza
> ```


> Pobieranie więcej niż jednego indeksy - używamy **listy indeksów**
> ```{python}
>  matrix [  [LISTA WIERSZY]  ,  [LISTA KOLUMN] ]
> ```

In [11]:
# weź 3-i wiersz, pierwszą kolumnę (jedna wartość)
matrix[2, 0]

7

In [12]:
# Weż wszystkie wartości z wierszy w kolumnie 2-ej
matrix[:, 1]

array([2, 5, 8])

In [13]:
# Weź wszystkie wartości z kolumn dla wiersza 1-ego
matrix[0, :]

array([1, 2, 3])

In [14]:
# Dla wiersza 1 i 3 weź wartości z kolumny 2 i 3

matrix[[0, 2] , [1,2] ]

array([2, 9])

# Operacje na macierzach i wektorach

Wektory i macierze mają szereg wbudowanych operacji, jak sumy/średnie itp.
Możemy się do nich odwoływać:

> Przez bibliotekę:
> ```{python}
> np.FUNKCJA(  macierz  )
>```

albo

> Bezpośrednio **z obiektu macierzy**
> ```{python}
>  macierz.FUNCJA() 
> ```

Używając tych funkcji, pamiętajmy **względem czego je aplikujemy!!!***. 

> axis=0 - oznacza liczenie po kolumnach, jedna po drugiej
> axis =1 - oznacza liczenie po wierszach, jeden po drugim

In [18]:
matrix.sum(axis=0) # suma kolumn, wywołanie z obiektu macierzy

array([12, 15, 18])

In [19]:
np.sum(matrix, axis=0) # to samo, ale wywołanie z biblioteki

array([12, 15, 18])

In [20]:
matrix.sum(axis=1) # Suma wierszy, wywołanie z obiektu macierzy

array([ 6, 15, 24])

In [21]:
np.sum(matrix, axis=1) # to samo, ale wywołanie z biblioteki

array([ 6, 15, 24])

Bardzo ważne są pewne konkretne operacje matematyczne na wektorach i macierzach oraz ich interakcje.
I tak:

> **[Iloczyn skalarny](https://pl.wikipedia.org/wiki/Iloczyn_skalarny)** - iloczyn i suma poszczególnych elementów wektorów/macierzy:
> ```{python}
> np.dot(vec, matrix) # wywołanie z biblioteki
> vec.dot(matrix)     # wywołanie z obiektu
> ```

> **[Iloczyn diadyczny](https://pl.wikipedia.org/wiki/Iloczyn_diadyczny)** - iloczyn tensorowy wektora kolumnowego z wektorem wieszowym (strasznie to brzmi, ale jest bardzo proste). Zestawienie "stojącego" i "leżacego" wektora - iloczyn elementów na ich przecięciu.
> ```{python}
> np.outer(vec1, vec2) # wywołanie z biblioteki - jedyny sposób
> ```

> **[Iloczyn Hadamarda](https://pl.wikipedia.org/wiki/Mno%C5%BCenie_macierzy#Iloczyn_Hadamarda)** - kolejna straszna nazwa, opisująca najprostszy iloczyn - mnożenie przez siebie odpowiadających sobie elementów obu wektorów i macierzy. UWAGA! Muszą mieć takie same kształty.
> ```{python}
> vec1 * vec2
> matrix1 * matrix2
> vec1 + vec2
> ```
> *etc.*

Mając dane:

In [33]:
matrix1 = matrix
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matrix2 = np.array([
    
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
    
])
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [28]:
vec1 = vec
vec1

array([10, 20, 30])

In [29]:
vec2 = np.array([2,3,4])
vec2

array([2, 3, 4])

In [30]:
# Iloczyn skalarny wektorów:

vec1.dot(vec2) # albo np.dot(vec1, vec2)

200

In [34]:
# Iloczyn skalarny macierzy: wiersz z jednej*kolumna z drugiej i suma elementów
matrix1.dot(matrix2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [35]:
# Iloczyn diadyczny wektorów:

np.outer(vec1, vec2)

array([[ 20,  30,  40],
       [ 40,  60,  80],
       [ 60,  90, 120]])

In [36]:
# Iloczyn Hadamarda wektorów
vec1 * vec2

array([ 20,  60, 120])

In [37]:
# Iloczyn Hadamarda macierzy:

matrix1 * matrix2

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])